M48
; DRILL file {KiCad 8.0.1-8.0.1-1~ubuntu22.04.1} date 2024-09-21T11:56:40+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-09-21T11:56:40+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1-8.0.1-1~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X135.985Y-63.3
X135.985Y-69.08
T2
X91.37Y-59.64
X117.23Y-72.76
M30
